name: wallet
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^0.3.8
  flutter_mobx: ^0.3.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.3.1
  mobx_codegen: ^0.3.9

flutter:
  fonts:
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat-Light.ttf 
        - asset: assets/fonts/Montserrat-Bold.ttf

  
  uses-material-design: true

  assets:
    - assets/images/