name: wallet
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^01.2.1+4
  flutter_mobx: ^1.1.0+2
  dio: ^3.0.10
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.4
  mobx_codegen: ^1.1.1+3

flutter:
  fonts:
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat-Light.ttf 
        - asset: assets/fonts/Montserrat-Bold.ttf

  
  uses-material-design: true

  assets:
    - assets/images/