name: wallet
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat-Light.ttf 
        - asset: assets/fonts/Montserrat-Bold.ttf

  
  uses-material-design: true

  assets:
    - assets/images/